# CMake generated Testfile for 
# Source directory: N:/Development/Dev_Base/proj-9.3.0/test/unit
# Build directory: N:/Development/Dev_Base/proj-9.3.0/msvc/test/unit
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(proj_errno_string_test "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/Debug/proj_errno_string_test.exe")
  set_tests_properties(proj_errno_string_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;98;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(proj_errno_string_test "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/Release/proj_errno_string_test.exe")
  set_tests_properties(proj_errno_string_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;98;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(proj_errno_string_test "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/MinSizeRel/proj_errno_string_test.exe")
  set_tests_properties(proj_errno_string_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;98;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(proj_errno_string_test "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/RelWithDebInfo/proj_errno_string_test.exe")
  set_tests_properties(proj_errno_string_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;98;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
else()
  add_test(proj_errno_string_test NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(proj_angular_io_test "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/Debug/proj_angular_io_test.exe")
  set_tests_properties(proj_angular_io_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;108;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(proj_angular_io_test "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/Release/proj_angular_io_test.exe")
  set_tests_properties(proj_angular_io_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;108;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(proj_angular_io_test "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/MinSizeRel/proj_angular_io_test.exe")
  set_tests_properties(proj_angular_io_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;108;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(proj_angular_io_test "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/RelWithDebInfo/proj_angular_io_test.exe")
  set_tests_properties(proj_angular_io_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;108;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
else()
  add_test(proj_angular_io_test NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(proj_context_test "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/Debug/proj_context_test.exe")
  set_tests_properties(proj_context_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;118;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(proj_context_test "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/Release/proj_context_test.exe")
  set_tests_properties(proj_context_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;118;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(proj_context_test "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/MinSizeRel/proj_context_test.exe")
  set_tests_properties(proj_context_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;118;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(proj_context_test "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/RelWithDebInfo/proj_context_test.exe")
  set_tests_properties(proj_context_test PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;118;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
else()
  add_test(proj_context_test NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(proj_test_cpp_api "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/Debug/proj_test_cpp_api.exe")
  set_tests_properties(proj_test_cpp_api PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;154;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(proj_test_cpp_api "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/Release/proj_test_cpp_api.exe")
  set_tests_properties(proj_test_cpp_api PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;154;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(proj_test_cpp_api "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/MinSizeRel/proj_test_cpp_api.exe")
  set_tests_properties(proj_test_cpp_api PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;154;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(proj_test_cpp_api "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/RelWithDebInfo/proj_test_cpp_api.exe")
  set_tests_properties(proj_test_cpp_api PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;154;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
else()
  add_test(proj_test_cpp_api NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(gie_self_tests "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/Debug/gie_self_tests.exe")
  set_tests_properties(gie_self_tests PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;164;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(gie_self_tests "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/Release/gie_self_tests.exe")
  set_tests_properties(gie_self_tests PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;164;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(gie_self_tests "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/MinSizeRel/gie_self_tests.exe")
  set_tests_properties(gie_self_tests PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;164;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(gie_self_tests "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/RelWithDebInfo/gie_self_tests.exe")
  set_tests_properties(gie_self_tests PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;164;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
else()
  add_test(gie_self_tests NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_network "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/Debug/test_network.exe")
  set_tests_properties(test_network PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;186;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_network "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/Release/test_network.exe")
  set_tests_properties(test_network PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;186;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_network "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/MinSizeRel/test_network.exe")
  set_tests_properties(test_network PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;186;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_network "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/RelWithDebInfo/test_network.exe")
  set_tests_properties(test_network PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;186;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
else()
  add_test(test_network NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_defmodel "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/Debug/test_defmodel.exe")
  set_tests_properties(test_defmodel PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;196;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_defmodel "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/Release/test_defmodel.exe")
  set_tests_properties(test_defmodel PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;196;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_defmodel "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/MinSizeRel/test_defmodel.exe")
  set_tests_properties(test_defmodel PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;196;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_defmodel "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/RelWithDebInfo/test_defmodel.exe")
  set_tests_properties(test_defmodel PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;196;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
else()
  add_test(test_defmodel NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_tinshift "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/Debug/test_tinshift.exe")
  set_tests_properties(test_tinshift PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;206;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_tinshift "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/Release/test_tinshift.exe")
  set_tests_properties(test_tinshift PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;206;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_tinshift "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/MinSizeRel/test_tinshift.exe")
  set_tests_properties(test_tinshift PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;206;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_tinshift "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/RelWithDebInfo/test_tinshift.exe")
  set_tests_properties(test_tinshift PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;206;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
else()
  add_test(test_tinshift NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test_misc "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/Debug/test_misc.exe")
  set_tests_properties(test_misc PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;216;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test_misc "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/Release/test_misc.exe")
  set_tests_properties(test_misc PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;216;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test_misc "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/MinSizeRel/test_misc.exe")
  set_tests_properties(test_misc PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;216;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test_misc "N:/Development/Dev_Base/proj-9.3.0/msvc/bin/RelWithDebInfo/test_misc.exe")
  set_tests_properties(test_misc PROPERTIES  ENVIRONMENT "PROJ_SKIP_READ_USER_WRITABLE_DIRECTORY=YES;PROJ_DATA=N:/Development/Dev_Base/proj-9.3.0/msvc/data/for_tests;PROJ_SOURCE_DATA=N:/Development/Dev_Base/proj-9.3.0/data" _BACKTRACE_TRIPLES "N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;216;add_test;N:/Development/Dev_Base/proj-9.3.0/test/unit/CMakeLists.txt;0;")
else()
  add_test(test_misc NOT_AVAILABLE)
endif()
